version: '3.9'

services:
  social_network:
    container_name: social_network
    image: social_network
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      ConnectionStrings__SocialNetwork: "Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres-social-network
    image: postgres:17
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #PGDATA Посмотреть нужен ли
    volumes:
      - social-network-db:/var/lib/postgresql/data
      - ./Data/Migrations:/docker-entrypoint-initdb.d  #TODO: Init scripts -> to flyway

volumes:
  social-network-db: